export const catalogProducts = [
  {
    slug: "kowac-andes-boot",
    name: "Andes Boot",
    brand: "Kowac",
    price: 149.9,
    compareAtPrice: 179.9,
    isFeatured: true,
    type: "zapatos",
    categoryLabel: "Botas",
    images: [],
  },
  {
    slug: "kowac-sierra-loafer",
    name: "Sierra Loafer",
    brand: "Kowac",
    price: 119.9,
    type: "zapatos",
    categoryLabel: "Loafers",
    images: [],
  },
  {
    slug: "kowac-urban-oxford",
    name: "Urban Oxford",
    brand: "Kowac",
    price: 129.9,
    compareAtPrice: 154.9,
    isFeatured: true,
    type: "zapatos",
    categoryLabel: "Oxfords",
    images: [],
  },
  {
    slug: "kowac-coastal-sandal",
    name: "Coastal Sandal",
    brand: "Kowac",
    price: 89.9,
    type: "zapatos",
    categoryLabel: "Sandalias",
    images: [],
  },
  {
    slug: "kowac-heritage-jacket",
    name: "Heritage Jacket",
    brand: "Kowac",
    price: 134.5,
    compareAtPrice: 159.9,
    isFeatured: true,
    type: "ropa",
    categoryLabel: "Chaquetas",
    images: [],
  },
  {
    slug: "kowac-atelier-shirt",
    name: "Atelier Shirt",
    brand: "Kowac",
    price: 79.9,
    type: "ropa",
    categoryLabel: "Camisas",
    images: [],
  },
  {
    slug: "kowac-studio-trouser",
    name: "Studio Trouser",
    brand: "Kowac",
    price: 94.9,
    type: "ropa",
    categoryLabel: "Pantalones",
    images: [],
  },
  {
    slug: "kowac-essentials-polo",
    name: "Essentials Polo",
    brand: "Kowac",
    price: 64.9,
    type: "ropa",
    categoryLabel: "Polos",
    images: [],
  },
];
